remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gem "github-pages", group: :jekyll_plugins
github:
  zip_url: https://github.com/Eduardo-vsouza/rp3/releases/tag/Rp3_v1.1.0
  GitHub: https://github.com/Eduardo-vsouza/rp3